"""Add blacklisted_tokens table

Revision ID: 1ab0a0ae05d8
Revises: f26a7845b6ea
Create Date: 2025-03-24 12:13:13.924215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab0a0ae05d8'
down_revision: Union[str, None] = 'f26a7845b6ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
