"""Add status and other fields to todos table

Revision ID: 7f7fb27e026a
Revises: 15ec17189d90
Create Date: 2025-05-06 15:18:20.758105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f7fb27e026a'
down_revision: Union[str, None] = '15ec17189d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the task_assignments table
    op.create_table('task_assignments',
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['todo_id'], ['todos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('todo_id', 'user_id', 'role')
    )
    
    # Add new columns to todos table
    op.add_column('todos', sa.Column('status', sa.String(), server_default='todo', nullable=False))
    op.add_column('todos', sa.Column('priority', sa.String(), server_default='medium', nullable=False))
    op.add_column('todos', sa.Column('estimated_hours', sa.Float(), nullable=True))
    op.add_column('todos', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('todos', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True))
    op.add_column('todos', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=True))
    op.add_column('todos', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todos', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'project_id')
    op.drop_column('todos', 'updated_at')
    op.drop_column('todos', 'created_at')
    op.drop_column('todos', 'due_date')
    op.drop_column('todos', 'estimated_hours')
    op.drop_column('todos', 'priority')
    op.drop_column('todos', 'status')
    op.drop_table('task_assignments')
    # ### end Alembic commands ###
