"""add to_user_id to recommendation link tables

Revision ID: fcfe56a6a2c6
Revises: 6d62bf86c931
Create Date: 2025-04-15 01:25:04.092575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcfe56a6a2c6'
down_revision: Union[str, None] = '6d62bf86c931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.add_column('project_recommendations', sa.Column('to_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_project_recommendations_to_user_id'), 'project_recommendations', ['to_user_id'], unique=False)
    op.create_foreign_key(op.f('fk_project_recommendations_to_user_id_users'), 'project_recommendations', 'users', ['to_user_id'], ['id'], ondelete='CASCADE')

    op.add_column('team_recommendations', sa.Column('to_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_team_recommendations_to_user_id'), 'team_recommendations', ['to_user_id'], unique=False)
    op.create_foreign_key(op.f('fk_team_recommendations_to_user_id_users'), 'team_recommendations', 'users', ['to_user_id'], ['id'], ondelete='CASCADE')

    op.add_column('post_recommendations', sa.Column('to_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_post_recommendations_to_user_id'), 'post_recommendations', ['to_user_id'], unique=False)
    op.create_foreign_key(op.f('fk_post_recommendations_to_user_id_users'), 'post_recommendations', 'users', ['to_user_id'], ['id'], ondelete='CASCADE')

def downgrade() -> None:
    op.drop_constraint(op.f('fk_post_recommendations_to_user_id_users'), 'post_recommendations', type_='foreignkey')
    op.drop_index(op.f('ix_post_recommendations_to_user_id'), table_name='post_recommendations')
    op.drop_column('post_recommendations', 'to_user_id')

    op.drop_constraint(op.f('fk_team_recommendations_to_user_id_users'), 'team_recommendations', type_='foreignkey')
    op.drop_index(op.f('ix_team_recommendations_to_user_id'), table_name='team_recommendations')
    op.drop_column('team_recommendations', 'to_user_id')

    op.drop_constraint(op.f('fk_project_recommendations_to_user_id_users'), 'project_recommendations', type_='foreignkey')
    op.drop_index(op.f('ix_project_recommendations_to_user_id'), table_name='project_recommendations')
    op.drop_column('project_recommendations', 'to_user_id')






# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     # op.alter_column('teams', 'leader_id',
#     #            existing_type=sa.INTEGER(),
#     #            nullable=False)
#     # op.drop_constraint('fk_teams_leader_id_users', 'teams', type_='foreignkey')
#     # op.create_foreign_key(None, 'teams', 'users', ['leader_id'], ['id'])
#     # ### end Alembic commands ###
#
#
# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(None, 'teams', type_='foreignkey')
#     op.create_foreign_key('fk_teams_leader_id_users', 'teams', 'users', ['leader_id'], ['id'], ondelete='SET NULL')
#     op.alter_column('teams', 'leader_id',
#                existing_type=sa.INTEGER(),
#                nullable=True)
#     # ### end Alembic commands ###
