"""make to_user_id not nullable in recommendations

Revision ID: 91c7d88e3719
Revises: d435ba322078
Create Date: 2025-04-15 22:46:30.764384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c7d88e3719'
down_revision: Union[str, None] = 'd435ba322078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recommendations', 'to_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('teams', 'leader_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'leader_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('recommendations', 'to_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
