"""Add posts relationship to Project model

Revision ID: a01b6d66c7c7
Revises: d6cf95260b38
Create Date: 2025-02-06 18:52:26.556073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a01b6d66c7c7'
down_revision: Union[str, None] = 'd6cf95260b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
