"""add media fields to messages

Revision ID: ef72293edbdd
Revises: add_read_to_messages
Create Date: 2025-04-21 22:38:23.264135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef72293edbdd'
down_revision: Union[str, None] = 'add_read_to_messages'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
               ALTER TABLE conversations
                   DROP CONSTRAINT IF EXISTS conversations_project_id_fkey
               """)
    op.execute("""
               ALTER TABLE conversations
                   DROP CONSTRAINT IF EXISTS conversations_team_id_fkey
               """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уникальный ID чата',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('conversations_id_seq'::regclass)"))
    op.alter_column('conversations', 'type',
               existing_type=postgresql.ENUM('direct', 'project', 'team', name='conversationtype'),
               type_=sa.String(),
               comment=None,
               existing_comment='Тип чата',
               existing_nullable=False)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    #op.drop_constraint('conversations_project_id_fkey', 'conversations', type_='foreignkey')
    #op.drop_constraint('conversations_team_id_fkey', 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'team_id')
    op.drop_column('conversations', 'project_id')
    op.add_column('messages', sa.Column('media_url', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('media_type', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('media_name', sa.String(), nullable=True))
    op.alter_column('messages', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уникальный ID сообщения',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               comment=None,
               existing_comment='Текст сообщения',
               existing_nullable=False)
    op.alter_column('messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Время отправки',
               existing_nullable=True)
    op.drop_index('ix_messages_timestamp', table_name='messages')
    op.alter_column('teams', 'leader_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'leader_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_messages_timestamp', 'messages', ['timestamp'], unique=False)
    op.alter_column('messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               comment='Время отправки',
               existing_nullable=True)
    op.alter_column('messages', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               comment='Текст сообщения',
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.INTEGER(),
               comment='Уникальный ID сообщения',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('messages', 'media_name')
    op.drop_column('messages', 'media_type')
    op.drop_column('messages', 'media_url')
    op.add_column('conversations', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Связь с проектом'))
    op.add_column('conversations', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Связь с командой'))
    op.create_foreign_key('conversations_team_id_fkey', 'conversations', 'teams', ['team_id'], ['id'])
    op.create_foreign_key('conversations_project_id_fkey', 'conversations', 'projects', ['project_id'], ['id'])
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('conversations', 'type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('direct', 'project', 'team', name='conversationtype'),
               comment='Тип чата',
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.INTEGER(),
               comment='Уникальный ID чата',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('conversations_id_seq'::regclass)"))
    # ### end Alembic commands ###
