"""Add project_applications and project_members tables

Revision ID: e8325e404ec5
Revises: c78ac0f87ab7
Create Date: 2025-01-31 16:26:43.675073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8325e404ec5'
down_revision: Union[str, None] = 'c78ac0f87ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
